# define the two containers
services:
  db-psql:
    # pull the postgres image from DockerHub
    image: postgres:15.2
    container_name: db-psql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 5

  web-app:
    #build: .
    image: carshop:latest
    container_name: ttyeri/carshop:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-psql:5432/postgres
    depends_on:
      db-psql:
        # waiting for the database to be ready
        condition: service_healthy
    volumes:
      - ./python/app:/carshop/app

volumes:
  # to persist the database tables
  db-volume: