
name: CI/CD Carshop-API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Prepare python env for test
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install test dependencies
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install httpx pytest

    # Run test     
    - name: Test with pytest
      run: |
        pytest
    
    # Build and push image 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

    # Update deployment manifest and commit
    - name: Update GitOps repository
      shell: bash
      env:
        GIT_TOKEN: ${{secrets.CR_PAT}}
      run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/ttala/carshop-gitops.git gitops
          cd gitops

          IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
          sed -i "s#image:.*#image: $IMAGE#g" deployment.yaml

          # Commit changes
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push -f https://${GIT_TOKEN}@github.com/ttala/carshop-gitops.git main
